# Generated by Django 4.0 on 2024-05-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_company_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_code',
            field=models.ForeignKey(blank=True, help_text='Your Company', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
