# Generated by Django 4.0 on 2024-05-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_company_code'),
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_code',
            field=models.ForeignKey(blank=True, help_text='Your Company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
    ]
