# Generated by Django 4.0 on 2024-05-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_code',
            new_name='company',
        ),
    ]
