# Generated by Django 4.0 on 2024-06-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='description',
            field=models.TextField(blank=True, help_text='RawMaterial Description', null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_weight',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('KG', 'Kilogram'), ('CM', 'Centimeter'), ('LITRE', 'Litre')], default='NORMAL', help_text='Enter the measuring weight for raw_material', max_length=10),
        ),
    ]
