# Generated by Django 3.2.19 on 2024-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Enter City', max_length=50)),
                ('country', models.CharField(help_text='Enter Country', max_length=50)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField(blank=True, help_text='Enter contact no', max_length=11, null=True)),
                ('email', models.EmailField(help_text='Enter email', max_length=254)),
                ('website', models.CharField(blank=True, help_text='Enter your website url', max_length=200, null=True)),
            ],
            options={
                'ordering': ['contact_no'],
            },
        ),
    ]
