# Generated by Django 3.2.19 on 2024-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(blank=True, help_text='Enter contact no', null=True),
        ),
    ]
