# Generated by Django 5.0.6 on 2024-05-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20240511_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.CharField(blank=True, help_text='Enter contact no', max_length=11, null=True),
        ),
    ]
