# Generated by Django 5.0.6 on 2024-05-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_contact_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact_no'], 'verbose_name_plural': 'Contacts'},
        ),
    ]
