# Generated by Django 4.0 on 2024-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_address_options_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Enter your website url', null=True),
        ),
    ]
