# Generated by Django 4.0 on 2024-05-17 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product Name', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_materials', models.ManyToManyField(blank=True, related_name='products', to='raw_materials.Rawmaterial')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ['product_name'],
            },
        ),
    ]
