# Generated by Django 4.0 on 2024-05-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(blank=True, related_name='products', through='products.ProductRawMaterial', to='raw_materials.Rawmaterial'),
        ),
        migrations.AddField(
            model_name='productrawmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productrawmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.rawmaterial'),
        ),
    ]
