# Generated by Django 4.0 on 2024-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(to='raw_materials.Rawmaterial'),
        ),
    ]
