# Generated by Django 4.0 on 2024-06-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productrawmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrawmaterial',
            name='unit_weight',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product Description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('KG', 'Kilogram'), ('CM', 'Centimeter'), ('LITRE', 'Litre')], default='NORMAL', help_text='Enter the measuring weight for product', max_length=10),
        ),
    ]
