# Generated by Django 4.0 on 2024-05-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
        ('products', '0002_product_raw_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='raw_materials',
            field=models.ManyToManyField(blank=True, to='raw_materials.Rawmaterial'),
        ),
    ]
