# Generated by Django 4.0 on 2024-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productrawmaterial_unit_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrawmaterial',
            name='required_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='raw material required to make the product'),
        ),
    ]
