# Generated by Django 4.0 on 2024-06-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0003_rawmaterial_price'),
        ('products', '0004_alter_productrawmaterial_required_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrawmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rawmaterial', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rawmaterial', to='raw_materials.rawmaterial'),
        ),
    ]
