# Generated by Django 3.2.19 on 2024-05-11 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_auto_20240511_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company Name', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='contacts.address')),
                ('contact_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='contacts.contact')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
