# Generated by Django 4.0 on 2024-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(help_text='Company Name', max_length=200),
        ),
    ]
