# Generated by Django 5.0.6 on 2024-05-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address_details',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='contact_details',
            new_name='contact',
        ),
    ]
