# Generated by Django 5.0.6 on 2024-05-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_address_details_company_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name_plural': 'Companies'},
        ),
    ]
