# Generated by Django 5.0.6 on 2024-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(help_text='Company Name', max_length=200, unique=True),
        ),
    ]
