# Generated by Django 4.0 on 2024-05-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_company_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_code',
        ),
    ]
