# Generated by Django 4.0 on 2024-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(default='0123456789', help_text='Enter a 10 digit code that will be used as company code', max_length=10, unique=True),
        ),
    ]
