# Generated by Django 4.0 on 2024-05-17 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_website'),
        ('companies', '0010_alter_company_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies', to='contacts.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies', to='contacts.contact'),
        ),
    ]
