# Generated by Django 4.0 on 2024-05-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_address_alter_company_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=10),
        ),
    ]
