# Generated by Django 4.0 on 2024-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
