# Generated by Django 4.0 on 2024-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_warehouse_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='available_quantity',
            field=models.IntegerField(blank=True, default=0, help_text='Quantity Available in warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='unit_weight',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('KG', 'Kilogram'), ('CM', 'Centimeter'), ('LITRE', 'Litre')], default='NORMAL', help_text='Enter the measuring unit', max_length=10),
        ),
    ]
