# Generated by Django 4.0 on 2024-06-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_remove_warehouseproduct_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='unit_weight',
        ),
    ]
