# Generated by Django 4.0 on 2024-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_remove_warehouseproduct_unit_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Quantity Available in warehouse'),
        ),
    ]
