# Generated by Django 5.0.6 on 2024-05-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['store_name'], 'verbose_name_plural': 'Stores'},
        ),
    ]
