# Generated by Django 5.0.6 on 2024-05-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address_details',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='contact_details',
            new_name='contact',
        ),
    ]
