# Generated by Django 4.0 on 2024-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_storeproduct_unit_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total Products Available in store'),
        ),
    ]
