# Generated by Django 4.0 on 2024-05-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
        ('stores', '0006_store_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser'),
        ),
    ]
