# Generated by Django 4.0 on 2024-06-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productrawmaterial_product_and_more'),
        ('stores', '0006_alter_store_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='stores.store'),
        ),
    ]
