# Generated by Django 4.0 on 2024-05-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_website'),
        ('accounts', '0005_customuser_profile_picture_and_more'),
        ('companies', '0011_alter_company_address_alter_company_company_code_and_more'),
        ('stores', '0007_alter_store_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['id'], 'verbose_name_plural': 'Stores'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_name',
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='contacts.address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='accounts.customuser'),
        ),
    ]
