# Generated by Django 4.0 on 2024-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_storeproduct_product_alter_storeproduct_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='sold_amount',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total Products Sold by store'),
        ),
    ]
