# Generated by Django 4.0 on 2024-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_store_options_remove_store_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
