# Generated by Django 4.0 on 2024-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productrawmaterial_alter_product_raw_materials_and_more'),
        ('stores', '0010_storeproduct_store_products_storeproduct_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='stores', through='stores.StoreProduct', to='products.Product'),
        ),
    ]
