# Generated by Django 4.0 on 2024-05-21 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_materials', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier Name', max_length=200)),
                ('industry', models.CharField(blank=True, help_text='Industry', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Supplier Description', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='suppliers', to='contacts.address')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='suppliers', to='contacts.contact')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRawmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('rawmaterial', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='raw_materials.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='rawmaterials',
            field=models.ManyToManyField(blank=True, related_name='suppliers', through='suppliers.SupplierRawmaterial', to='raw_materials.Rawmaterial'),
        ),
    ]
