# Generated by Django 4.0 on 2024-06-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_supplierrawmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierrawmaterial',
            name='unit_weight',
        ),
    ]
