# Generated by Django 4.0 on 2024-06-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_company_name'),
        ('suppliers', '0004_alter_supplierrawmaterial_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='industry',
            field=models.CharField(blank=True, help_text='Type of industry', max_length=100, null=True),
        ),
    ]
