# Generated by Django 4.0 on 2024-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_rawmaterial_description_rawmaterial_unit_weight'),
        ('suppliers', '0005_supplier_company_alter_supplier_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='rawmaterials',
            field=models.ManyToManyField(blank=True, null=True, related_name='suppliers', through='suppliers.SupplierRawmaterial', to='raw_materials.Rawmaterial'),
        ),
    ]
