# Generated by Django 4.0 on 2024-06-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_rawmaterial_description_rawmaterial_unit_weight'),
        ('suppliers', '0006_alter_supplier_rawmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='rawmaterials',
            field=models.ManyToManyField(blank=True, related_name='suppliers', through='suppliers.SupplierRawmaterial', to='raw_materials.Rawmaterial'),
        ),
        migrations.AlterField(
            model_name='supplierrawmaterial',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='available quantity supplier has'),
        ),
        migrations.AlterField(
            model_name='supplierrawmaterial',
            name='rawmaterial',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierrawmaterial', to='raw_materials.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='supplierrawmaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierrawmaterial', to='suppliers.supplier'),
        ),
    ]
